### PR TITLE
Fix server hitch warning

### PR DESCRIPTION
**Pull request by Tinky124**

### CODE REVIEW

**Comment by LazarusOfTheFallen** [comment]
You need to specify what removing this does if you want this to be merged.

**Comment by Tinky124** [comment]
> You need to specify what removing this does if you want this to be merged.

Removing this will fix server hitch warning and server side profiler MS.. because every second it selecting database and ESX.GetPlayers().. also it have loop.. so its very bad on high servers lije 100+ players.

**Comment by LazarusOfTheFallen** [comment]
And do you lose any functionality at all when you remove it? If so, then you need to have an alternative beforehand.

**Review by Tinky124 — COMMENTED** [review]
Fixed

**Comment by LazarusOfTheFallen** [comment]
Much better, thank you

**Comment by yolobrandon01** [comment]
image
Still having high hitches.. On ESX version 1.2FINAL

image

**Comment by LordXenaroth** [comment]
This helped but esx_status still give hitch warnings

**Pull request merged**
