### PR TITLE
Restore original status value

### PR DESCRIPTION
**Pull request by CodeCool-Developer**
restore original value  after create status from on trigger event 'esx_status:registerStatus'

### CODE REVIEW

**Comment by Gellipapa** [comment]
@CodeCool-Developer Hi! Any use case?

**Comment by CodeCool-Developer** [comment]
1. To ensure that the original status is used to return the original value after esx_status:registerStatus, the original status will be used. This is because the original code was written before I made any changes. If TriggerEvent is called to esx_status:loaded, but esx_status:registerStatus is called back late, the original loop written before will not be able to return the original status value.

2. In some cases, the status is not registered immediately after TriggerEvent('esx_status:loaded'), which causes the status to be the default value that was registered.

**Comment by CodeCool-Developer** [comment]
My edit ensures that every time the status is registered, it will always receive the original status value if it exists in the OriginalStatus variable.

**Comment by Gellipapa** [comment]
Hi! @CodeCool-Developer Thanks for this implementation, merged.

**Pull request merged**
